[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "synapse-pkg"
version = "0.1.1"
description = "Knowledge graph extraction library powered by LLMs"
readme = "README.md"
requires-python = ">=3.10"

authors = [
    { name = "Piyush Garg" }
]

dependencies = [    
    "google-generativeai",
    ]